//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shop_Test_Servers
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Text.Json.Serialization;

    public partial class Products
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Article { get; set; }
        public double Cost { get; set; }
        public int Count { get; set; }
        public Nullable<int> Image { get; set; }
        public string Description { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Images Images { get; set; }
    }
}
